name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Node.js and cache dependencies
      - name: Setup Node.js | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm run test

      # Build the project (if applicable)
      - name: Build project
        run: npm run build

      # Build the project (if applicable)
      - name: Build docker image
        run: docker build -t nestjs_docker_rocketseat .
